### ISSUE TITLE
krakend version

### ISSUE THREAD

**Issue by ricmoreira** [devopsfaith/krakend-jose#10]
Is it possible to update dependency for KrakenD 0.7.0 or create a release for that KrakenD version?

**Comment by kpacha** [comment]
we bump new versions when required.

you can do the same we did at the KrakenD-CE:

```
[[override]]
  version = "0.7.0"
  name = "github.com/devopsfaith/krakend"
```

**Comment by ricmoreira** [comment]
ok. Thank you @kpacha
