### ISSUE TITLE
Pass through jwt data to backend

### ISSUE THREAD

**Issue by aserrallerios** [devopsfaith/krakend-jose#14]
Hello,

I'm fairly new to oauth and jwt validation and hope you don't mind if I ask a question about oauth flow here.

I'm using krakend with jose to validate a jwt token issued by okta system. Everything works fine and the token is validated, but, as my api gateway -> backend communication is secure, I want to propagate some of the jwt data to the backend, maybe using a request header. In particular, my backend needs the email of the user doing the request.

Is this a typical scenario? Can jose addon solve it? If not: do I need another krakend piece? I need something not even covered by krakend scope?

**Comment by kpacha** [comment]
Hi @aserrallerios and welcome to the KrakenD community.

This component signs and validates JWT, it does not extract a thing from them. If you want to access the JWT info at your backends, you should pass the `Authorization` header (https://www.krakend.io/docs/endpoints/parameter-forwarding/#headers-forwarding). The backend just needs to decode the base64 encoded info and take whatever it wants from it.

Cheers

**Comment by aserrallerios** [comment]
Oh, that'll do, thanks! 

I'm slowly dispelling some of the magic around oauth and jwt, so sorry for the out of place question :)

**Comment by kpacha** [comment]
don't worry! we're happy to help.

btw, you can also join our slack channel (https://gophers.slack.com/messages/krakend)

**Comment by Oxonium** [comment]
> so I am passing both `Authorization` and `Cookie` to the backend and returning a 401 from my backend if the cookie key is present.

Hello ! I'm curious on how you did that ? Do you have some memories of it ? Thanks !

**Comment by benatkin** [comment]
In the Krakend designer you can select which headers to pass - I pass `Cookie` and `Authorization` 

https://github.com/ResourcesCo/experimental-express-gitea-app/blob/main/packages/api/gateway/api-development.json#L86

Then in my HTTP handler I simply reject any requests that have the `access_token` cookie and only use the `Authorization` header

https://github.com/ResourcesCo/experimental-express-gitea-app/blob/main/packages/api/app/controllers/auth.js#L6
