### ISSUE TITLE
Put HS256 key in krakend configuration

### ISSUE THREAD

**Issue by dcommisso** [devopsfaith/krakend-jose#21]
Hello Krakend team,
I'm trying to configure krakend to validate JWT tokens signed with HS256 key. I don't like the idea to serve the key using an endpoint (especially since it's a symmetric key and I need an extra effort to be 100% sure that nobody else except krakend can access the key). Is there a way to avoid using jwk-url parameter and put the key in krakend configuration? Am I missing something here?
Thanks in advance!

**Comment by kpacha** [comment]
@dcommisso, so far, the `jwks-url` param must be a http(s) endpoint. Managing secrets is out of the scope of this project, so storing and serving the JWK should be delegated to some external service.

Maybe we could add support for the [gocloud secrets](https://gocloud.dev/howto/secrets/) package to the JWK loader, so the JWK could be published as an encrypted blob.

**Comment by dcommisso** [comment]
It would be great!
Thanks.

**Comment by kpacha** [comment]
@dcommisso we are working on https://github.com/devopsfaith/krakend-jose/pull/41, feedback is welcome!
