### ISSUE TITLE
Instead of jwk-url is there is a way to directly load public key input ?

### ISSUE THREAD

**Issue by devansvd** [devopsfaith/krakend-jose#26]
JWT's can be validated offline without the need for internet. Instead of retrieving public key from the `jwk_url` to verify the signature is there is a way to directly load the public key ? may as a input via text box. 

Sample input: **_Basically Offline validation_**
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhAj9OCZd0XjzOIad2VbUPSMoVK1X8hdD2Ad+jUXCzhZJf0RaN6B+79AW5jSgceAgyAtLXiBayLlaqSjZM6oyti9gc2M2BXzoDKLye+Tgpftd72Zreb4HpwKGpVrJ3H3Ip5DNLSD4a1ovAJ6Sahjb8z34T8c1OCnf5j70Y7i9t3y/j076XIUU4vWpAhI9LRAOkSLqDUE5L/ZdPmwTgK91Dy1fxUQ4d02Ly4MTwV2+4OaEHhIfDSvakLBeg4jLGOSxLY0y38DocYzMXe0exJXkLxqHKMznpgGrbps0TPfSK0c3q2PxQLczCD3n63HxbN8U9FPyGeMrz59PPpkwIDAQAB
-----END PUBLIC KEY-----
```

**Comment by kpacha** [comment]
see https://github.com/devopsfaith/krakend-jose/issues/21

**Comment by devansvd** [comment]
@kpacha how about an option to store it in config file itself and use at our own risk ?

**Comment by kpacha** [comment]
@devansvd we are working on https://github.com/devopsfaith/krakend-jose/pull/41, feedback is welcome!
