### ISSUE TITLE
Expired token throw token expired error

### ISSUE THREAD

**Issue by devansvd** [devopsfaith/krakend-jose#27]
Currently if passing a expired token it throws `401: Unauthorized`. This is hard to debug sometimes, For expired token error message might be useful along the unauthorized part.

`401 - Token expired, Unauthorized`

**Comment by kpacha** [comment]
that information can be found in the logs:

```
Error #01: square/go-jose/jwt: validation failed, token is expired (exp)
```

It's not reported to the client in order to reduce the attack surface

**Comment by devansvd** [comment]
@kpacha got it thanks
