### ISSUE TITLE
Support for Space Delimited Scopes

### ISSUE THREAD

**Issue by pjcunnin** [devopsfaith/krakend-jose#32]
Currently the JWT validator is unable to handle spec defined scope claims via the `roles` and `roles-key` configuration when they are space delimited.

Example:
```
{
  "user": "Test User",
  ...
  "scope": "orders refunds",
 ...
}
```

**Comment by alombarte** [comment]
Hi Peter,

The expected format is a list (`scope: ["orders", "refunds"]`).
https://www.krakend.io/docs/authorization/jwt-validation/#jwt-validation-settings

Why would you add an alternative format? Could you justify it?

Thanks

**Comment by alombarte** [comment]
We will add this option as per your suggestion, so we can accept both formats.

Thanks for opening the issue

**Comment by vetorialnet** [comment]
Hi,
I'm looking for a way to generate an ACL based on "scope", and/or "roles". How can I do that?
Thanks

**Comment by kpacha** [comment]
@vetorialnet check the documentation: https://www.krakend.io/docs/authorization/jwt-validation/#validation-process

**Comment by vetorialnet** [comment]
Can I configure even for scopes?
