### ISSUE TITLE
Roles_key only support parsing string list in claims

### ISSUE THREAD

**Issue by slowr** [devopsfaith/krakend-jose#42]
I have a JWT that has the current user role in a string and not in a list of strings like this:
```
{
  "user_info": {
    "accessType": "REGISTERED|IP,
    "accountId": ...,
  },
```

I set the roles_key to be `user_info.accessType` but it seems that the current implementation of roles_key only support a list of strings. Would it make sense to also support parsing it as a string if it's not a list?

**Comment by kpacha** [comment]
> We face similar issue, we have role as a plain string value in the payload.
>
> Current behavior seems to reject the role with 403, even though the value matches.

That's weird because I've added a test for your case and it's working

**Comment by OndraM** [comment]
Weird indeed. But there is no other information in the log besides 403, is it possible to debug this somehow?

We ale also using older krakend version on this particular instance, so maybe if this was changed in last few versions, we may not be using it.

**Comment by kpacha** [comment]
that should be the case. please upgrade it and check it again

**Comment by alombarte** [comment]
Closing. In case it does not work with the last version please reopen.
