### ISSUE TITLE
Krakend 1.1.1 not accepting roles

### ISSUE THREAD

**Issue by nvlan** [devopsfaith/krakend-jose#50]
Hello, I've tried to make roles to work using jose-validator but for some reason I'm not able to match any role. The endpoint config is:
`      "endpoint": "/rests-partners-gateway/rests-partners-accounts/info/",`
`      "method": "GET",`
`      "output_encoding": "json",`
`       "timeout": "900ms",`
`       "headers_to_pass": [ "*" ],`
`      "querystring_params": [ "*" ],`
`      "cache_ttl": "0s",`
`      "extra_config": {`
`              "github.com/devopsfaith/krakend-jose/validator": {`
`                  "jwk-url" : "https://partners-foo.auth0.com/.well-known/jwks.json",`
`                  "roles_key": "https://partners.foo.com/roles",`
`                  "roles": ["krakend"],`
`                  "disable_jwk_security": true,`
`                  "alg" : "RS256"`
`              }`
`      },`

And my token has the following payload:
`{`
`  "https://partners.rappi.com/roles": [`
`    "krakend"`
`  ],`
`  "nickname": "carlos.castro",`
`  "name": "carlos.castro@foo.com",`
`  "picture": "https://s.gravatar.com/avatar/077bc3b0517eb18354e0f3ebfb6a0220?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fca.png",`
`  "updated_at": "2020-11-26T17:56:18.066Z",`
`(...)`
`}`
If I remove the roles_key and roles config, all requests with a valid token go through and those that don't receive a 401. But when I add the roles_key and roles directives, I receive a 403 (that according to [this](https://github.com/devopsfaith/krakend-jose/pull/18) PR means the token does not contain the required role. I've checked the playground config and it looks identical (the roles_key being a URL, and such) but still can't get it to work (and running krakend with the -d option does not give any extra output sadly). Am I missing something?
Thanks a lot, and kind regards.

**Comment by kpacha** [comment]
notice the difference:
```
"roles_key": "https://partners.foo.com/roles",
```
and
```
"https://partners.rappi.com/roles": [
"krakend"
],
```

the configured key is not the one present at the jwt

**Comment by nvlan** [comment]
I'm terribly sorry, I meant to obfuscate with "foo" in both places. The key says "foo" (or "rappi" for that matter) both in the config and in the JWT...

**Comment by nvlan** [comment]
Hello,
Upon further testing I suspect that there is something in the token that makes krakend unable to properly parse it. I am using a shorter-payload token that has the following content:
```
{
  "iss": "https://nico-test.us.auth0.com/",
  "sub": "oZ4Qwz7G3ep60tcNblYttUWFl4NqD3tT@clients",
  "aud": "https://el.pulpo.com",
  "iat": 1606424904,
  "exp": 1606511304,
  "azp": "oZ4Qwz7G3ep60tcNblYttUWFl4NqD3tT",
  "gty": "client-credentials",
  "permissions": [
    "foo",
    "bar"
  ]
}
```
With the following endpoint config:
```
      "endpoint": "/rests-partners-gateway/rests-partners-accounts/info/",
      "method": "GET",
      "output_encoding": "no-op",
      "extra_config": {
              "github.com/devopsfaith/krakend-jose/validator": {
                  "roles_key": "permissions",
                  "roles": ["bar"],
                  "jwk-url" : "https://nico-test.us.auth0.com/.well-known/jwks.json",
                  "disable_jwk_security": true,
                  "alg" : "RS256"
              }
      },
```
In this case, kraken is able to check the "permissions" key and verify if the role "bar" is in there. When using a different role in the token, I get a 403 (as expected).

Thing is, with the following token:
```
{
  "https://partners.foo.com/roles": [
    "krakend"
  ],
  "nickname": "carlos.castro",
  "name": "carlos.castro@foo.com",
  "picture": "https://s.gravatar.com/avatar/077bc3b0517eb18354e0f3ebfb6a0220?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fca.png",
  "updated_at": "2020-11-26T17:56:18.066Z",
  "email": "carlos.castro@foo.com",
  "email_verified": true,
  "iss": "https://partners-foo.auth0.com/",
  "sub": "auth0|5dcc9086defff70f095a1610",
  "aud": "A1YdFI6mIhG0NjozZsjISe1BDx7FdfJR",
  "iat": 1606413378,
  "exp": 1606449378,
  "at_hash": "c5WgSZhJAAqS_uH9pgFMVg",
  "nonce": "PZ~o1BijmVPeFYK-a0xjBeICMfJfm03k"
}
```
and the following endpoint config:
```
      "endpoint": "/rests-partners-gateway/rests-partners-accounts/info2/",
      "method": "GET",
      "output_encoding": "no-op",
      "extra_config": {
              "github.com/devopsfaith/krakend-jose/validator": {
                  "roles_key": "https://partners.foo.com/roles",
                  "roles": ["krakend"],
                  "jwk-url" : "https://partners-foo.auth0.com/.well-known/jwks.json",
                  "disable_jwk_security": true,
                  "alg" : "RS256"
              }
      },
```
I get a 403 every time, as if the token didn't have the role "krakend" in the key "https://partners.foo.com/roles". Besides attempting to change the key for something else/simpler, is there anything in the JWT that would cause this strange behavior?
Thanks a lot, kind regards.
