### ISSUE TITLE
Cannot use JWT key for url_pattern in backend

### ISSUE THREAD

**Issue by nvlan** [devopsfaith/krakend-jose#57]
Hello,

I was trying to use a JWT value for the url_pattern in a certain endpoint's backend, and for some keys it works (for other keys does not). I have the following token:
```
{
  "https://partners.foo.com/roles": [
    "krakend",
    "PORTAL_KAM"
  ],
  "https://partners.foo.com/email": "carlos.castro@foo.com",
  "nickname": "carlos.castro",
  "name": "carlos.castro@foo.com",
  "picture": "https://s.gravatar.com/avatar/077bc3b0517eb18354e0f3ebfb6a0220?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fca.png",
  "updated_at": "2021-02-01T14:07:22.375Z",
  "email": "carlos.castro@foo.com",
  "email_verified": true,
  "iss": "https://partners-foo.auth0.com/",
  "sub": "auth0|5dcc9086defff70f095a1610",
  "aud": "A1YdFI6mIhG0NjozZsjISe1BDx7FdfJR",
  "iat": 1612202845,
  "exp": 1612238845,
  "at_hash": "o9ACF3tTbfLFepKuZPWqtg",
  "nonce": "6_mZthv1SNyRYGZBkah5mRL1ZpF4z07y"
}
```
When I configure the url_pattern as:

`"url_pattern": "/rests-partners-accounts/partners/{JWT.email}/countries",`

I see that the requests are correctly routed to /rests-partners-accounts/partners/carlos.castro/countries. However, when I try to configure the url_pattern like this:

`"url_pattern": "/rests-partners-accounts/partners/{JWT.https://partners.foo.com/email}/countries",`

I see that the request tries to go to /rests-partners-accounts/partners/%7BJWT.https://partners.foo.com/email%7D/countries , as if krakend could not locate the key https://partners.foo.com/email. 

Any help would be much appreciated, kind regards.

**Comment by kpacha** [comment]
In deed, the custom claims with namespace can't be injected into the url pattern as the regular ones, but there is a workaround: pass the auth header and use a lua script for the url manipulation as in this example: https://github.com/devopsfaith/krakend-ce/blob/master/tests/fixtures/lua/collection.lua#L1-L10

**Comment by kpacha** [comment]
duplicates https://github.com/devopsfaith/krakend-ce/issues/273
