### ISSUE TITLE
JWT Validation. roles_key different from "roles" not working?

### ISSUE THREAD

**Issue by fd-rey** [devopsfaith/krakend-jose#60]
**Describe the bug**
Roles validation responds with 403 if the roles-key if different from "roles". 
If I use the role-key "roles" in my endpoint and in my token, the validation works properly, but if I use for example the role-key "apiRoles" in the endpoint and in the token, the validation returns 403.

If I remove the roles validation config, the token validation goes well so it's not a problem related with jwk keys or token headers.

**To Reproduce**
1. Configuration used
Endpoint:
```json
{
      "endpoint": "/api/v2/events",
      "method": "GET",
      "output_encoding": "no-op",
      "extra_config": {
        "github.com/devopsfaith/krakend-jose/validator": {
          "alg": "RS256",
          "jwk-url": "http://myapi.com/well-known/jwks.json",
          "disable_jwk_security":true,
          "roles-key":"apiRoles",
          "roles":["admin","readOnly"]
        }
      },
      "backend": [
        {
          "url_pattern": "/api/v2/events",
          "encoding": "no-op",
          "method": "POST",
          "host": ["localhost:8070"]
        }
      ]
    }
```
Content of the generated token payload:
```json
{
  "apiRoles": [
    "readOnly",
    "admin"
  ],
  "iat": 1614852485,
  "exp": 1615212485
}
```

**Expected behavior**
I expect the jose validator to extract the roles list from the "apiRoles" claim in the token payload. And use them to match the roles defined in the endpoint.

**Logs**
```
[GIN] 2021/03/04 - 11:13:04 | 403 |    5.263572ms |             ::1 | GET      "/api/v2/events"
```

**Additional context**
The token is sent in the Authorization: Bearer header.

**Comment by taik0** [comment]
Hi @fd-rey 
I moved the issue to this repo since it's about JOSE and not about the KrakenD framework.

**Comment by fd-rey** [comment]
Okay thanks @taik0

**Comment by taik0** [comment]
I've been testing with the unittests of krakend-jose and seems to work without problems using `apiRoles` as a key.

https://github.com/devopsfaith/krakend-jose/blob/ee6196d50d0779a7d8ae8cbd49c4cb98169113fb/jose_test.go#L31-L58

Can you give us more information to try to reproduce the problem?

**Comment by fd-rey** [comment]
Thanks @taik0, which kind of information could help?

**Comment by alombarte** [comment]
@fd-rey The key in the config is `roles_key` and not `roles-key`.

Give it a spin with this change.

**Comment by fd-rey** [comment]
Ouch... indeed that was the problem, thank you @alombarte! I think that I got confused because of `jwt-url` key which uses `-`.
Maybe it would be better to change it to jwt_url in a future?

I guess that if  `roles` key exists in the validator config, it uses "roles" as default value for the `roles_key` and that's why it was working even with the bad `roles-key` key.

**Comment by alombarte** [comment]
Yes, you are right, there is no consistency in the naming. We are aware of the problem.
Glad it helped
