### ISSUE TITLE
Propagate Claims does not overwrite existing headers

### ISSUE THREAD

**Issue by adrianMark** [devopsfaith/krakend-jose#62]
Using the "propagate claims" functionality e.g. to extract a field from an incoming JWT Token and forwarding it as a HTTP header, incoming request headers with the same key are not overwritten by the module. 

Example:
- Situation: Propagate claims is set to extract the field "sub" from the JWT and forward it as a custom header "Jwt-Sub". 
- Scenario: An incoming request already contains a header "Jwt-Sub" with a value of "abc" 
- Result: The module passes the original value ("abc") to the backend instead of replacing the incoming value as expected

In effect every client can force a header value into the system

**Comment by adrianMark** [comment]
Hi Guys, do you have any idea if the fix #63 is going to be released?

**Comment by alombarte** [comment]
Hi Adrian,

If you want to see this included in the KrakenD container we release it around 4 times/year. We just released 1.3.0.

**Comment by adrianMark** [comment]
Thanks for getting back to me. Do you have a rough notion of when the next release is going to be?

**Comment by alombarte** [comment]
We are too far to say. Sometimes there is a patch and we make a release faster, but if everything goes as usual probably in summer (July). But it's so far that this comment becomes unrealistic.
If you are willing to use the code in master branch and compile yourself it will happen faster.
