### ISSUE TITLE
Can't enable JWT validation and signing on the same endpoint

### ISSUE THREAD

**Issue by hashibuto** [devopsfaith/krakend-jose#66]
It seems as though even though I've enabled both of these `extra_config`, only one will be picked up by krakenD

```
"extra_config": {
        "github.com/devopsfaith/krakend-jose/validator": {
          "alg": "HS256",
          "jwk-url": "http://localhost:9001/jwk",
          "cache": true,
          "roles_key": "roles",
          "roles": [
            "admin",
            "user"
          ],
          "propagate-claims": [
            ["ident", "x-ident"],
            ["user_id", "x-user-id"],
            ["org_id", "x-organization-id"],
            ["jti", "x-jti"]
          ],
          "disable_jwk_security": true
        },
        "github.com/devopsfaith/krakend-jose/signer": {
          "alg": "HS256",
          "kid": "me@my.com",
          "keys-to-sign": [
            "access_token",
            "refresh_token"
          ],
          "jwk-url": "http://localhost:9001/jwk",
          "disable_jwk_security": true
        }
      }
    },
```

My use case is for that of a refresh token.  Using the signed token to access a specific endpoint which then generates another access token and signs it on the way out.  I have the access token endpoint working, and I've set up both signing and validation on different endpoints, but during krakend startup there does not seem to be any way to get both a validater and signer on the same endpoint.  No error is expressed, but the logs will indicate that either one has been successfully setup (if I supply only one, either works).   When both are supplied, only the signer is accepted.  Thanks.

**Comment by kpacha** [comment]
hi @hashibuto ,

I've swapped the factories so now the verifier can be wrapping the signer

thanks for the heads up!

**Comment by pstefou** [comment]
@kpacha Hey, that's great.  Thanks for getting on that so quickly!

**Comment by hashibuto** [comment]
@kpacha Hey, that's great.  Thanks for getting on that so quickly!
