### ISSUE TITLE
Support for Firebase Auth API

### ISSUE THREAD

**Issue by crjacinro** [devopsfaith/krakend-jose#73]
Is there a complete support for Firebase Auth API for Krakend-jose (token validation)? 

Usually, the clients will authenticate directly to firebase and gets a user token, and that token is sent to the backend. Then, the backend verifies that token through the firebase sdk (depends on the language used - in this case, Go).  Is there a way to move this logic completely to krakend so all api requests are validated in the API gateway layer?  How does krakend verify the token in firebase sdk?  

I noticed it was mentioned in this [documentation](https://www.krakend.io/docs/authorization/jwt-validation/) but there were no other documentation to achieve this step-by-step.

**Comment by kpacha** [comment]
I'm not familiar with firebase auth api, but as stated at the linked article:

> KrakenD does not need to validate all calls using your IdP. KrakenD validates every incoming call’s signature and it doesn’t make token introspection (asking the IdP data about the token owner).

so, if your IdP requires introspection, you'll need to implement your customized middleware

**Comment by crjacinro** [comment]
Ok thanks. Can you expound a little further regarding this section?

> KrakenD does not generate the tokens itself. Still, you can plug it into any SaaS or self-hosted Identity Provider (IdP) using industry standards (e.g.: Auth0, Azure AD, Google Firebase, Keycloak, etc.)

How to plug these IdPs into Krakend endpoints or  how to implement our **customized** **middleware** as you mentioned?

**Comment by kpacha** [comment]
The minimal validation configuration requires just the algorithm and the JWK url. Beyond that, you can add more constraints to your validation as described at https://www.krakend.io/docs/authorization/jwt-validation/#jwt-validation-settings

If you want to implement a custom plugin, please check this article: https://www.krakend.io/docs/extending/writing-plugins/#writing-router-plugins-http-handler

If you want to write a custom middleware, you should be familiar with:
- https://pkg.go.dev/github.com/devopsfaith/krakend/proxy#Middleware
- https://pkg.go.dev/github.com/devopsfaith/krakend/proxy#Proxy
- https://pkg.go.dev/github.com/devopsfaith/krakend/proxy#Factory
