### ISSUE TITLE
The deprecation of github.com/auth0-community/go-auth0 breaks build

### ISSUE THREAD

**Issue by gunturaf** [devopsfaith/krakend-jose#88]
As per https://community.auth0.com/t/community-repo-deprecation-auth0-go/64665 , it was said that this line https://github.com/devopsfaith/krakend-jose/blob/90b8fe32a9fd493ded8e74d1fbcaddd0e8674ffb/go.mod#L6 has been deprecated since long ago by the new https://github.com/go-auth0/auth0 , last week IIRC the deprecated repo was still available so no error happened, but as of today the deprecated repository (github.com/auth0-community/go-auth0) seems to have return 404 (looks like the repo has been deleted in the end).

Do you accept a PR for this matter?

**Comment by gunturaf** [comment]
edit: the latest repository was here https://github.com/auth0/go-auth0

**Comment by kpacha** [comment]
hi @gunturaf . we were aware of the deprecation notice but we did not keep track of the date (the process of releasing v2 was very demanding). I think the easiest way to fix this could be to publish a fork of the original repo at our github organization until we can invest the resources required for dropping the dependency and moving to the new lib.

once the fork is published, a single "replace" line on the go.mod of the krakend-jose and krakend-ce projects should be enough to keep everything up and running

> Do you accept a PR for this matter?

of course. all contributions are welcome!

**Comment by kpacha** [comment]
Mirror created at https://github.com/devopsfaith/go-auth0
Replace added to this project and to the CE itself

cheers!
