### ISSUE TITLE
Bearer Token Validation - JWT HS256

### ISSUE THREAD

**Issue by ricmoreira** [devopsfaith/krakend-jose#9]
Hello Krakend team:
I'm trying to run Krakend with Docker, with JWT middleware and I don't know what am I doing wrong for getting the following error:

> Error #01: no Keys has been found" 

This is my configuration file:

```json
{
  "version": 2,
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "host": [ "http://authentication:8081", "https://jsonplaceholder.typicode.com" ],
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level":  "DEBUG",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true
    },
    "github_com/devopsfaith/krakend-cors": {
      "allow_origins": [],
      "allow_methods": [ "POST", "GET", "DELETE", "PUT", "OPTIONS" ],
      "allow_headers": ["Origin","Authorization","Content-Type", "Access-Control-Allow-Origin", "locale", "accept", "x-requested-with", "Cache-Control"],
      "expose_headers": ["Content-Length", "Content-Type", "Cache-Control", "Authorization"],
      "max_age": "12h",
      "allow_credentials": true
    }
  },
  "endpoints": [
    {
      "endpoint": "/api/authentication/login",
      "method": "POST",
      "backend": [
        {
          "host": [ "http://authentication:8081" ],
          "url_pattern": "/api/authentication/login"
        }
      ]
    },
    {
      "endpoint": "/protected/resource",
      "extra_config": {
          "github.com/devopsfaith/krakend-jose/validator": {
              "alg": "HS256",
              "jwk-url": "http://authentication:8081/jwk",
              "disable_jwk_security": true
          }
      },
      "backend": [
          {
            "host": "https://jsonplaceholder.typicode.com",
            "url_pattern": "/todos/1"
          }
      ]
    }
  ]
}
```

The endpoint that provides the jwk is returning this response when calling 

> http://authentication:8081/jwk

```json
{
    "keys": [
        {
            "kty": "oct",
            "kid": "key1",
            "k": "1Aj0dBGu5OYigpE2-JAynzBy6hz7H3XpmIpJZiB0XUQ",
            "alg": "HS256"
        }
    ]
}
```

That same key is used to sign the JWT token that is sent on successfull login:

```
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZSIsImlzcyI6Imh0dHBzOlwvXC9jMmlkLmNvbSIsImV4cCI6MTU0MjkyNjc5N30.ksE9yj4R9GkWDS17fkskn45KQMA_zbQfhDxO7A-lQoA
```

When I call the protected resource I call with that same token:

```
GET /protected/resource HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZSIsImlzcyI6Imh0dHBzOlwvXC9jMmlkLmNvbSIsImV4cCI6MTU0MjkyNjc5N30.ksE9yj4R9GkWDS17fkskn45KQMA_zbQfhDxO7A-lQoA
cache-control: no-cache
Postman-Token: e8ffcc64-6500-4d4c-b628-2ce6837abbb4

```

And I allways get an Unauthorized response:

```
gateway_1_d11464d89157 | [GIN] 2018/11/22 - 22:47:04 | 401 |      9.8294ms |      172.25.0.1 | GET      /protected/resource
gateway_1_d11464d89157 | Error #01: no Keys has been found
```

Can you help me with this? Thanks.

**Comment by kpacha** [comment]
hi, @ricmoreira !

That log message appears when your token has no `kid` header with the key ID.
 
Inspecting the sample token you provided with the jwt.io debugger you can see the headers:
```
{
  "alg": "HS256"
}
```

In order to be able to verify their signature, you should issue your JWTs with the key ID (as defined at your JWK, `"kid":"key1"`)

Cheers!

**Comment by ricmoreira** [comment]
You're the man @kpacha ! Thanks!

**Comment by Foxcool** [comment]
If I use HMAC-SHA 256 algo, why I need to have jwk-url?

I want to set symmetric key on my auth service and my krakenD based gateway by config, and check:
- mandatory only check signature by sectret key
- check roles (if used in extra-config)
- check userID (also)
- another checks by jwt claims.

**Comment by kpacha** [comment]
Hi, @Foxcool 

the JWK are consumed from remote services because we choose to reject the 'problems' related to key management (like security and key rotation) and also, we focused on keeping the JOSE module as small and simple as possible.

### security

keeping your secrets in your codebase is not best practice (or in the CI pipe or the filesystem). From the [RFC 7517](https://tools.ietf.org/html/rfc7517#section-9.1):

> One should place no more trust in the data cryptographically secured by a key than in the method by which it was obtained and in the trustworthiness of the entity asserting an association with the key. Any data associated with a key that is obtained in an untrusted manner should be treated with skepticism.

That is why we recommend adding the fingerprints of the certificate used by the JWK server so the KrakenD can verify the source of the keys it is using.

### operational complexity

orchestrating a cluster of KrakenD nodes should not require anything but deploying a small binary with a single config file

### other key managers and backends

adding support for other backends and more complex key managers like vault is in the long-term roadmap

cheers!

**Comment by Foxcool** [comment]
Ok. But, if we use symmetric algo (like HMAC-SHA), we need to store key secretly (only private key. No public keys or certificates). This case is not implemented?

**Comment by alombarte** [comment]
Hi @Foxcool, I think this will clear your doubts:

https://www.krakend.io/docs/authorization/jwt-signing/ <-- Sign tokens with the private key
https://www.krakend.io/docs/authorization/jwt-validation/ <-- Validate tokens with the public key

**Comment by Foxcool** [comment]
Hi, @alombarte!
I read this docs. But I don't know, how can I do validation with symmetric algo like HMAC-SHA256. This algo haven't Public key, if I don't mistake.

**Comment by kpacha** [comment]
@Foxcool I think we should move the conversation over to [slack](https://gophers.slack.com/messages/krakend)... because your questions are not related to the issue

cheers

**Comment by Foxcool** [comment]
ok, thank you!

**Comment by bariis** [comment]
```
package jwt

import (
	"github.com/golang-jwt/jwt"
	"time"

	"github.com/google/uuid"
)

type token struct {
	UserID uuid.UUID `json:"user_id"`
	jwt.StandardClaims
}

type TokenResponse struct {
	AccessToken token `json:"access_token"`
}

func GenerateToken(userID uuid.UUID) token {
	return token{
		UserID: userID,
		StandardClaims: jwt.StandardClaims{
			ExpiresAt: time.Now().Add(time.Hour * 72).Unix(),
			Audience:  "http://krakend:5000",
			Issuer:    "http://identityservice:5002",
		},
	}
}

```

This is how I issue my token and then Krakend signes itself. Where should I exactly put the `kid` insider token header?
